[build] # default master branch
  publish = "_site"
  command = "ELEVENTY_ENV=production eleventy"
  environment = { ELEVENTY_ENV = 'production' } # to enable Eleventy to know the environment

[context.preview] # 'preview' is the branch name
  publish = "_site"
  command = "ELEVENTY_ENV=preview eleventy"
  environment = { ELEVENTY_ENV = 'preview' } # to enable Eleventy to know the environment

[[redirects]]
  from = "/CPB_Christmas_Quiz_2020_-_Answer_Sheet.pdf"
  to = "/xmas-quiz/"
  status = 301
  force = true
